"""empty message

Revision ID: 9100947e9733
Revises: 83010a13e48b
Create Date: 2023-01-28 09:31:01.651182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9100947e9733'
down_revision = '83010a13e48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('price', sa.String(length=150), nullable=True),
    sa.Column('shipping_id', sa.String(length=150), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('car')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('vin', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('year', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('user_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], name='car_user_token_fkey'),
    sa.PrimaryKeyConstraint('id', name='car_pkey')
    )
    op.drop_table('item')
    # ### end Alembic commands ###
